# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Зміст відповіді')),
                ('true_answer', models.BooleanField(default=False, verbose_name='Правильна відповідь')),
            ],
            options={
                'verbose_name': 'Відповідь',
                'verbose_name_plural': 'Відповіді',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Вкажіть коротко (не більше 50-ти символів) зміст питання', max_length=50, null=True, verbose_name='Короткий зміст')),
                ('description', models.TextField(verbose_name='Зміст питання')),
            ],
            options={
                'verbose_name': 'Питання',
                'verbose_name_plural': 'Питання',
            },
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категорія питань')),
                ('description', models.TextField(blank=True, verbose_name='Опис категорії')),
            ],
            options={
                'verbose_name': 'Категорія питань',
                'verbose_name_plural': 'Категорії питань',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.ManyToManyField(blank=True, related_name='tests', to='quiz_app.Question', verbose_name='Питання до тесту')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тести',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.QuestionCategory', verbose_name='Категорія'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='quiz_app.Question', verbose_name='Номер питання'),
        ),
    ]
